/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./layout/components/AppHeader/index.vue')['default'];
    AppMain: typeof import('./layout/components/AppMain/index.vue')['default'];
    Breadcrumb: typeof import('./layout/components/AppHeader/components/Breadcrumb/index.vue')['default'];
    CustomForm: typeof import('./components/CustomForm/index.vue')['default'];
    ElAvatar: typeof import('element-plus/es')['ElAvatar'];
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb'];
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
    ElCol: typeof import('element-plus/es')['ElCol'];
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker'];
    ElDropdown: typeof import('element-plus/es')['ElDropdown'];
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem'];
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup'];
    ElOption: typeof import('element-plus/es')['ElOption'];
    ElRadio: typeof import('element-plus/es')['ElRadio'];
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
    ElSelect: typeof import('element-plus/es')['ElSelect'];
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    FormWrapper: typeof import('./components/CustomForm/components/FormWrapper/index.vue')['default'];
    Hamburger: typeof import('./layout/components/AppHeader/components/Hamburger/index.vue')['default'];
    InputNumber: typeof import('./components/InputNumber/index.vue')['default'];
    MenuItem: typeof import('./layout/components/Sidebar/MenuItem.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Screenfull: typeof import('./layout/components/AppHeader/components/Screenfull/index.vue')['default'];
    Sidebar: typeof import('./layout/components/Sidebar/index.vue')['default'];
    SideBarItem: typeof import('./layout/components/Sidebar/SideBarItem.vue')['default'];
    SidebarItemLink: typeof import('./layout/components/Sidebar/SidebarItemLink.vue')['default'];
    SideBarItemLink: typeof import('./layout/components/Sidebar/SideBarItemLink.vue')['default'];
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default'];
    TagsView: typeof import('./layout/components/TagsView/index.vue')['default'];
  }
}
